feat(tket2-hseries): Add `tket2.wasm` extension
CQCL/tket2 pull request #737
Opened 2024-12-27 11:06 UTC by doug-q

2025-01-06 09:54 UTC, lmondada approved these changes
Thanks @doug-q! It's always very fun to read your code, I learn a lot.

I don't have much useful feedback, other than that your design perfectly seems sound!

2025-01-06 09:54 UTC, lmondada commented on tket2-hseries/src/extension/wasm.rs
> +}
It might be that cargo fmt-ing this without the macro will break up some of the lines that are looking quite long at the moment.

2025-01-06 09:54 UTC, lmondada commented on tket2-hseries/src/extension/wasm.rs
> +/// TODO move this to `impl TypeArg` in `hugr-core`
Are you leaving this here for the moment because you do not want to make changes to `hugr-core` right now?

2025-01-06 09:54 UTC, lmondada commented on tket2-hseries/src/extension/wasm.rs
> +                    Signature::new(vec![module_type], vec![func_type]),
I'm a noob when it comes to define (parametrised) type signatures, so take this with a grain of salt. I notice that `Self::lookup` and `Self::call` use different ways to define the signatures returned, even though superficially they seem quite similar to me (`Signature::new` vs `FuncValueType::new`, `Type` vs `WasmType` etc)...

It would make it more readable if both code blocks were as similar as possible. If you can't use the same function calls & types for whatever reason, then maybe just put the respective function signatures in a comment -- it took me awhile to parse what they meant and had to refer several times back to the module docs (which were supremely useful btw).

2025-01-07 08:05 UTC, doug-q commented on tket2-hseries/src/extension/wasm.rs
> +}
Good tip, will do

2025-01-07 08:07 UTC, doug-q commented on tket2-hseries/src/extension/wasm.rs
> +/// TODO move this to `impl TypeArg` in `hugr-core`
It's more that I don't to condition this PR on a hugr release. I'll update to reference https://github.com/CQCL/hugr/issues/1837

2025-01-07 08:10 UTC, doug-q commented on tket2-hseries/src/extension/wasm.rs
> +                    Signature::new(vec![module_type], vec![func_type]),
I'll add comments as you suggest. re Signature + FuncValueType: the difference is that FuncValueType is allowed to have row variables in its input/output rows, while Signature must not (because we need to be able to count its ports).

Lookup returns a FuncValueType, while the callee of Call must have a signature (so that call can have a matching signature.

2025-01-08 10:22 UTC, mark-koch commented
The extension design looks good to me 👍

Just to clarify, the `WasmType::Context` is to track global state between wasm calls, right? So it's fine to call `GetContext` multiple times if you don't care about preserving that state?

2025-01-08 11:49 UTC, ss2165 reviewed
Looks good, add to https://github.com/CQCL/tket2/blob/99c7678ba26019d3bbe7c18a98572c5afba4720a/tket2-hseries/src/bin/tket2-hseries.rs#L9-L10 and regenerate extensions?

2025-01-08 11:49 UTC, ss2165 commented on tket2-hseries/src/extension/wasm.rs
> +//!
```suggestion
//!  `tket2.wasm.module`. It carries type args defining its signature, but not
//!  its name.
//!
```

2025-01-08 11:49 UTC, ss2165 commented on tket2-hseries/src/extension/wasm.rs
> +//!   - a `tket2.wasm.context` identifying where the call will exectue;
```suggestion
//!   - a `tket2.wasm.context` identifying where the call will execute;
```

2025-01-08 11:50 UTC, ss2165 commented
I would strongly prefer to separate out the breaking change in to a separate commit to main

2025-01-08 11:50 UTC, ss2165 requested changes
I would strongly prefer to separate out the breaking change in to a separate commit to main

2025-01-16 15:59 UTC, doug-q commented on tket2-hseries/src/extension/wasm.rs
> +                    Signature::new(vec![module_type], vec![func_type]),
I've added signatures in comments, but the syntax is quite made up. What do you think?

2025-01-16 16:18 UTC, ss2165 approved these changes
thanks for the changes

2025-01-16 16:18 UTC, ss2165 commented on tket2-hseries/src/extension/wasm.rs
> +      fn wasm_type(#[case] wasm_t: WasmType) {
looks like a formatting issue

2025-01-16 17:10 UTC, merged